### ISSUE TITLE
Copying remotes with odd name errors and doesn't copy

### ISSUE THREAD

**Issue by DeveloperMikey** [Upbolt/Hydroxide#74]
Game it was tested on: https://www.roblox.com/games/4036494886/2X-Gun-Simulator
Example: https://user-images.githubusercontent.com/45462729/179472234-2ad3b385-c9f6-486a-aaaf-31d07839e76f.mp4

**Comment by z4xi** [comment]
looks like they have some sort of anti-rspy script or something set up, because it's complaining that what its trying to read is an "Invalid UTF-8 code", which it is. when you look at the remotes, its all replaced with weird squares and foreign characters. 
(example: 
![chrome_zpqPj7cBj1](https://user-images.githubusercontent.com/36055611/183575160-23811161-873b-4bda-b77c-70519d2de2f8.png)

this is a script trying to interfere with any scripts like rspy, or hydroxide from trying to execute or read any remotes. correct me if im wrong though.
